### ISSUE TITLE
[locale] RangeError: Invalid time value

### ISSUE THREAD

**Issue by maxacarvalho** [ekoeryanto/vuepress-plugin-sitemap#16] opened 2019-04-16 12:02 UTC
Hello,

Apparently, there's an issue related to the `page.lastUpdated` data.  
At `index.js:54`   
```javascript
        const lastmodISO = page.lastUpdated
          ? new Date(page.lastUpdated).toISOString()
          : undefined
```

It throws an error like:  
```bash
 SITEMAP  Generating sitemap...
error vuepress-plugin-sitemap apply generated failed.
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at pages.forEach.page (/Users/maxacarvalho/Code/kooomo/it.intranet.kooomo.com/node_modules/vuepress-plugin-sitemap/index.js:54:40)
    at Array.forEach (<anonymous>)
    at generated (/Users/maxacarvalho/Code/kooomo/it.intranet.kooomo.com/node_modules/vuepress-plugin-sitemap/index.js:52:13)
    at AsyncOption.asyncApply (/Users/maxacarvalho/Code/kooomo/it.intranet.kooomo.com/node_modules/@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:21)
    at PluginAPI.applyAsyncOption (/Users/maxacarvalho/Code/kooomo/it.intranet.kooomo.com/node_modules/@vuepress/core/lib/node/plugin-api/index.js:272:32)
    at Build.render (/Users/maxacarvalho/Code/kooomo/it.intranet.kooomo.com/node_modules/@vuepress/core/lib/node/build/index.js:100:34)
error Command failed with exit code 1.
```

I'm using Vuepress version 1.x (`"vuepress": "^1.0.0-alpha.47"`)

Thanks.

**Comment by ekoeryanto** [comment] 2019-04-19 07:26
can you give us the output of the `page.lastUpdated` it self or have you a repo for us to reproduce the issue? 

Thanks.

**Comment by osdio** [comment] 2019-06-12 15:45
I think it caused by using `@vuepress/last-updated` which you change the page.lastUpdated.

Such as:

```
        [
          '@vuepress/last-updated',
          {
            transformer: (timestamp, lang) => {
              const moment = require('moment')
              moment.locale(lang)
              return moment(timestamp).fromNow()
            }
          }
        ]
```

**Comment by maxacarvalho** [comment] 2019-07-08 12:09
Hi, first of all I beg your pardon because of the lack of update about this issue, I was dealing with a different project for the past few months and couldn't check the issue.

I found that it, probably, has to do with localisation. Since I require to use `en-GB` as default language, the default output of the `last-updated` plugin will be something like `18/02/2019, 09:54:26` which will then throw the `RangeError: Invalid time value` exception when trying to `new Date(page.lastUpdated).toISOString() // new Date(18/02/2019, 09:54:26).toISOString()`

I added a fix like:

```
  plugins: [
    [
      '@vuepress/last-updated',
      {
        transformer: (timestamp, lang) => {
          const moment = require('moment')
          moment.locale(lang)
          return moment(timestamp).format("MMMM DD YYYY HH:mm")
        }
      }
    ],
    ['sitemap', { hostname: 'https://path-to-docs' }]
  ],
```

This issue could be solved with the localisation proposal, maybe using `moment` as a dependency.

**Comment by ekoeryanto** [comment] 2019-10-20 06:57
it fixed with `dateFormatter` option in v2.3.0

**Closed as completed by ekoeryanto** 2019-10-20 06:57 UTC

**Comment by Genuifx** [comment] 2020-08-28 09:23
"vuepress-plugin-sitemap": "^2.3.1",

bug still alive.

**Comment by Genuifx** [comment] 2020-08-28 09:33
The following code is work too~

```js
transformer: (timestamp, lang) => {
  return new Date(timestamp).toLocaleDateString();
}
```

**Comment by z979054461** [comment] 2024-03-16 14:27
This works for me.

```diff
        [
            'sitemap',
            {
                hostname: 'xxx',
+                dateFormatter: lastUpdated => {
+                   return new Date(lastUpdated.replace(/[上|下]午/g, '')).toISOString()
+                },
            },
        ],
```
