### ISSUE TITLE
not work while run vuepress dev

### ISSUE THREAD

**Issue by Genuifx** [ekoeryanto/vuepress-plugin-sitemap#9] opened 2018-12-25 09:51 UTC
not work while running `vuepress dev`, but do generate sitemap.xml after running `vuepress build`. Doesn't is a bug?

**Comment by ekoeryanto** [comment] 2018-12-25 15:17
@Genuifx, it's by design.

**Comment by ekoeryanto** [comment] 2019-01-03 18:05
I close it, feel free to reopen the issue if you want.

**Closed as completed by ekoeryanto** 2019-01-03 18:05 UTC
Labels: question
